mentos-team/MentOS

CMakeLists.txt
iso/boot/grub/grub.cfg

This requires the GRUB `grub-mkrescue` command to be available. Can be found in the grub2 / grub-pc packages on most Linux distributions.

Add cdrom.iso target

---

libc/src/unistd/waitpid.c
mentos/inc/process/scheduler.h
mentos/src/process/scheduler.c
mentos/src/system/signal.c

I noticed that with the current develop branch `waitpid` was not properly returning.
This is due to a change to the reported status now being the exit code instead of the process state (`EXIT_ZOMBIE`).
The first commit fixes `waitpid` by removing the now broken state check.
Secondly I was confused because normally exiting process with exit code > 0 where reported as terminated by a signal by the shell.
This is caused due to the exit() syscall not `properly` using the upper bytes (`0xff00`) of the exit code.

Improve process termination

---

iso/boot/grub/grub.cfg

During the cmake cleanup the bootloader binary was renamed from `kernel-bootloader.bin` to `bootloader.bin` however the GRUB boot menu entry was not updated accordingly.

Fix grub entry

---

mentos/src/fs/ext2.c

When creating new files in a directory the creating process must be allowed to write the directory not to read it.

vfs: fix permission check when creating files

---

mentos/src/fs/namei.c

creat.2 is supposed to be equivalent to open.2 with the flags O_WRONLY|O_CREAT|O_TRUNC.
However, in MentOS the fd returned by creat.2 has no flags whatsoever and is thus not writable.
Set the flags of the file descriptor before returning it.

creat: set flags in opened file descriptor

---

libc/src/unistd/exec.c

The current implementation always searches for the file in `PATH` if it is not an absolute path.
This prevents executing relative paths like `./executable`.
As specified by `man exec.3p` the p-family of exec functions only search if the filename does not contain slash '/' characters.

libc: prevent execvp to search for files containing '/'

---

programs/cat.c
programs/man.c

This pull request improves the file printing capabilities of the userspace tools.
It fixes the broken `read`/`puts` implementations in `cat` and `man`.
Additionally, it improves the exit code of cat to return 1 if one or more file could not be printed.

Improve text printing

---

mentos/src/fs/ext2.c

The first patch fixes a problem with a to big file size when creating new files.
@Galfurian you know the ext2 way better than me. Is it safe to remove the `inode.size` update from `ext2_allocate_inode_block` ?
The second patch ensures that the file size is correctly persisted for consecutive writes.
More in-depth explanations and reproducers can be found in the commit messages.
The third patch is optional and has currently no observable effect, because `vfs_file_t->length` is never used currently.

Fix some regressions in ext2_write

---

mentos/CMakeLists.txt
mentos/inc/drivers/keyboard/keymap.h
mentos/src/drivers/keyboard/keymap.c
mentos/src/kernel.c

The german umlauts are simply mapped to their "normal" vowals since we do not support unicode.

add german keymap

---

doc/syscall.md
libc/CMakeLists.txt
libc/inc/sys/unistd.h
libc/src/unistd/dup.c
mentos/inc/fs/vfs.h
mentos/src/fs/namei.c
mentos/src/fs/open.c
mentos/src/fs/vfs.c
mentos/src/system/syscall.c
programs/tests/CMakeLists.txt
programs/tests/t_dup.c

This is needed by the shell in order to redirect the output of commands.

Implement dup syscall

---

mentos/CMakeLists.txt
mentos/inc/drivers/mem.h
mentos/src/drivers/mem.c
mentos/src/kernel.c

The first and only memory device mounted at /dev/null discards all data written to it and always returns 0 bytes when read.

drivers: implement memory device driver

---

doc/syscall.md
files/usr/share/man/id.man
libc/inc/stddef.h
libc/inc/sys/unistd.h
libc/src/unistd/getgid.c
libc/src/unistd/getuid.c
libc/src/unistd/setgid.c
libc/src/unistd/setuid.c
mentos/inc/process/process.h
mentos/inc/system/syscall.h
mentos/src/process/process.c
mentos/src/process/scheduler.c
mentos/src/system/syscall.c
programs/CMakeLists.txt
programs/id.c

* Add a simple `id(1)` program.
* Follow POSIX by using signed types for `uid_t` and `gid_t`
*  Separate between effective and real IDs and implement the required syscalls
* Add support for `suid` and `sgid` binaries
* Misc cleanups

Implement user and group ID separation

---

doc/syscall.md
files/usr/share/man/chmod.man
files/usr/share/man/chown.man
libc/CMakeLists.txt
libc/inc/sys/unistd.h
libc/src/unistd/chmod.c
libc/src/unistd/chown.c
mentos/CMakeLists.txt
mentos/inc/fs/attr.h
mentos/inc/fs/vfs_types.h
mentos/src/fs/attr.c
mentos/src/fs/ext2.c
mentos/src/system/syscall.c
programs/CMakeLists.txt
programs/chmod.c
programs/chown.c

The fact that `chown` and `chmod` always resolve symlinks is handled in a separate later pull request.

support setting file attributes

---

libc/src/string.c
mentos/src/klib/string.c

The current implementations do not count the length of empty strings correctly.
The following buffer content `"\0foo\0"` is considered a string with length 4, because the iteration pointer is incremented before it is dereferenced to check for a null char.
Replace the broken `strlen` functions with the implementation of musl libc.
This fixes subtle bugs in the shell's code (e.g., `cmd_put("\0");`).

fix str[n]len implementations

---

libc/inc/fcntl.h
mentos/inc/fs/vfs.h
mentos/src/fs/ext2.c
mentos/src/fs/vfs.c

* Added `x` permissions check for directory traversal.
* Move the generic open checks to vfs.
* Make permission checks POSIX conform.
* Add currently unused exec permission check (will be used by a later pull request)

Fix and rework our permission permissions

---

files/usr/share/man/shell.man
programs/shell.c

This is a collection of all the shell patches I collected.
It included bugfixes next to new features, like redirects using `dup` or support for executing commands from files.
If the changes are too big let me know an I will break them into smaller pieces.

Improve shell

---

files/usr/share/man/echo.man
programs/echo.c

* Remove environment expansions (This is the shell's job)
* Support escape sequences
This should be merged after !43 especially after cada224b25454adcf0b413e2f530fe881ea33c5f.

Improve echo

---

.github/workflows/ubuntu.yml
CMakeLists.txt
iso/boot/grub/grub.cfg.runtests
mentos/src/kernel.c
mentos/src/system/panic.c
programs/CMakeLists.txt
programs/runtests.c
scripts/tapview

This patchset adds a TAP compliant test runner, capable of running as init process.
Additionally, a new cmake target is introduced running MentOS with different kernel command line to start `runtests` as init process.
Qemu is terminated by `runtest` or on a kernel `panic` in order to be usable as part of an github action.
The TAP test output written to the second serial port is checked using [tapview](https://gitlab.com/esr/tapview).

[RFC] add test runner and use it in the CI

---

files/etc/passwd
files/etc/shadow
libc/CMakeLists.txt
libc/inc/shadow.h
libc/src/shadow.c
programs/login.c

Move the passwords from the world-readable file /etc/passwd into the shadow file and provide new functions in libc to access the passwords when running as uid 0.
**TODO:** In order for this separation to be effective. We need a proper way to set realistic permissions in the rootfs
* Everything in / should be owned by uid=0
* Everything in /home/user should be owned by uid=1000

move passwords from /etc/passwd to /etc/shadow

---

mentos/src/process/process.c

Add executable permission check and return `-errno` from `__load_exectuable` to indicate the occurred error.

process: check if a file is executable before loading it

---

mentos/src/process/process.c
programs/shell.c

Only a single interpreter is allowed. Loops are not permitted. The interpreter path has to immediately follow the shebang.

support shebangs

---

mentos/src/fs/ext2.c
programs/runtests.c
programs/tests/CMakeLists.txt
programs/tests/t_big_write.c

- Improve `ext2_dump_inode output`;
- Rename `EXT2_INDIRECT_BLOCKS` to `EXT2_DIRECT_BLOCKS`;
- Simplify and fix `ext2_get_real_block_index`;
- Simplify and fix `ext2_read_inode_data`;
- Remove `indirect_blocks_index`, `doubly_indirect_blocks_index`, and `trebly_indirect_blocks_index` from the fs structure;
- Simplify and fix `ext2_set_real_block_index`, we were not saving the block in `ext2_set_real_block_index`;
- Create a stress test for big files;
- Fix `ext2_write_inode_data`;
- Add more comments to `ext2_allocate_block`;
- Add more logging messages where needed;

Fix ext2 read and write

---

mentos/inc/fs/vfs.h
mentos/src/fs/namei.c

Sorry for all the followup fixes. Hopefully, `resolve_path` is now done for the foreseeable future.

Fix resolve path

---

.github/workflows/ubuntu.yml
programs/cat.c

Currently our tests run for less than two minutes.
Adding a timeout of 10 minutes seems save and prevents wasting resources.

CI: add 10 minute timeout

---

mentos/src/fs/namei.c
mentos/src/fs/vfs.c

As mentioned in #75, this reverts the change in `vfs_open` and fixed the recursive `vfs_open` call in `resolve_path`.
Afterwards both
```
$ cat README
$ cat /home/user/README
```
work fine.

Fix `resolve_path` infinite loop

---

libc/src/grp.c
libc/src/pwd.c
programs/runtests.c
programs/tests/CMakeLists.txt
programs/tests/t_grp.c
programs/tests/t_pwd.c

Both functions comparing the user or group name did match on prefixes of the names and not only on literal matches.
This is fixed and tests are added to ensure this behavior.

Fix `getgrnam` and `getpwnam` functions

---

programs/ls.c

Now we only print the entries returned by `getdents`. Previously, if a directory contained 13 entries, the entries 2-12 would be printed twice, because they remain in the `dents` buffer.

fix listing big directories

---

files/usr/share/man/hier.man

Fix the explanation for `/usr/share` duplicated from `/usr/srv`. Add descriptions for the `/var` subtree.

man: correct and extend the file system hierarchy manual page

---

libc/inc/fcntl.h
libc/inc/sys/stat.h
libc/src/string.c
mentos/src/fs/ext2.c
mentos/src/fs/namei.c
mentos/src/fs/procfs.c
mentos/src/fs/vfs.c
mentos/src/io/video.c
mentos/src/ipc/ipc.c
mentos/src/klib/string.c
mentos/src/process/process.c
programs/ls.c
programs/shell.c
programs/stat.c
programs/tests/t_dup.c
programs/tests/t_msgget.c
programs/tests/t_semflg.c
programs/tests/t_semget.c
programs/tests/t_semop.c
programs/touch.c

This PR solves a couple of problems:
1. `readlink` was not opening the link correctly. Now it does;
2. Now both `stat` and `ls` correctly display the actual symlink path;
3. While fixing those commands, I noticed that ANSI coloring was wrong, so I fixed it.

Fix link management

---

mentos/src/fs/namei.c

`vfs_stat` returns 0 on success, but `__is_a_link` checked for `> 0` and therefore never detected any symbolic links.
Fixes: f384cb91f74200ad496e150c60d501a45329d1dd

fix __is_a_link helper

---

programs/shell.c

Previously `___expand_env` did calculate the input string length if it was not provided.
Now `___expand_env` expects that the `str_len` is provided. Update the documentation reflecting the actual behavior of the function. Fix `__expand_env` by calculating the length of the input string.
Fixes: 41bd1593a1ec436dd1655d9d74bd91268c997700

fix __expand_env not passing the input string length

---

exercises/ipc_messaging.md
libc/inc/assert.h
libc/inc/os_root_path.h
libc/inc/syslog.h
mentos/CMakeLists.txt
mentos/inc/io/debug.h
mentos/inc/io/video.h
mentos/inc/mem/buddy_system.h
mentos/inc/mem/slab.h
mentos/inc/mem/zone_allocator.h
mentos/inc/resource_tracing.h
mentos/src/io/proc_system.c
mentos/src/io/video.c
mentos/src/kernel.c
mentos/src/mem/buddy_system.c
mentos/src/mem/slab.c
mentos/src/mem/zone_allocator.c
mentos/src/resource_tracing.c
programs/login.c
programs/shell.c

- Now, the `/proc/meminfo` file also shows the status of the buddy systems for zone `ZONE_NORMAL` and `ZONE_HIGHMEM.`
- I've implemented screen scrolling inside the `video.c`; normally, it's a program that should handle scrolling. But here we have to do with what we have.
- I've moved the `RELATIVE_PATH` macro to its own file because it was needed in several places.
- I've added a draft for an exercise that asks to build a messaging system with its System Calls. I should try to feed it to an undergrad and see what happens...
That's it, have a lovely coding, you lot.

More info from meminfo info, screen scrolling

---

libc/src/shadow.c
mentos/CMakeLists.txt
mentos/inc/fs/vfs.h
mentos/src/drivers/ata.c
mentos/src/drivers/mem.c
mentos/src/fs/ext2.c
mentos/src/fs/pipe.c
mentos/src/fs/procfs.c
mentos/src/fs/vfs.c
mentos/src/mem/slab.c
programs/login.c

- Set up the resources monitoring for VFS files and ET2 files.
- Found a memory leack in shadow.c thanks to the resource monitor (good boy).

Monitor VFS and ET2 files. Fix memory leack.

---

mentos/CMakeLists.txt

raw `objcopy` command doesn't work - and does the wrong thing for cross-compiling anyway

using CMake variable for `objcopy` - required for macOS cross-compile
